<a href="https://colab.research.google.com/github/Javier-619/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy es una libreria de python.
Numpy se utiliza para trabajar con matrices
o arreglo
Numpy es la abreviatura de "python numerico"
tambien tiene funciones para trabajar en el dominio de algebra lineal, la transformada y las matrices
En python tenemos listas que sirven como matrices, pero son lentas de procesar.
Numpy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas
rapidos que las listas tradicionales.

In [1]:
#Primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,2,4,5])
print(arreglo)

[1 2 2 4 5]


Numpy como np
Numpy general mente se importa bajo el alias np. En python los alias son un nombre alternativo para referirse a la misma cosa

In [2]:
import numpy as np

arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprobando la version de numpy la cadena de la version se almacena
en el atributo__version__

In [4]:
import numpy as np

print(np.__version__)

2.0.2


Numpy creando matrices
crear un objeto ndarray de numpy
numpy se utiliza para tranajar con matrices el objeto de matriz se llama ndarray.
podemos crear un numpy ndarray utilizando la funcion array()

In [5]:
import numpy as np

arreglo = np.array(["Raul","Victor","Ana",])
print(arreglo)
print(type(arreglo))

['Raul' 'Victor' 'Ana']
<class 'numpy.ndarray'>


Dimensiones en matrices
una dimension en matrices es un nivel de profundidad de matriz(matrices anidadas) Una matriz anidada contiene matrices como elementos
Matrices 0/D. son elementos de una matriz. Cada valor de una matriz es una matriz pero 0-D. Ejemplo crea una matriz 0-D con un valor de 42

In [6]:
import numpy as np

arreglo = np.array(42)

print(arreglo)

42


Natrices 1-D
Una matriz que tiene matrices 0-D como elementos se denomina unidimensional o
1-D. Estas con las matrices mas comunes y basicas.
Ejemplo: crea una matriz de una dimension que tenga los valores 1,2,3,4,5

In [7]:
import numpy as np
arreglo = np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


Matrices de 2D una matriz que tiene matrices de una dimension como elementos se denomina matriz 2D. A menudo se utilizan para representar matices de segundo orden . Numpy tiene un submodulo completo dedicado a operaciones con matrices llamado numpy.mat
Ejemplo: Crea una matris de 2D que contenga dos matrices con los valores 123 y 456.

In [10]:
import numpy as np

arreglo = np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
una matriz que tiene matrices 2D se denomina matriz 3D.
Estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo: Crea una matriz 3D con dos matrices bidimensionales, ambas conteniendo
dos matrices con los valores 1,2,3 y 4,5,6

In [16]:
import numpy as np

arreglo = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
