<a href="https://colab.research.google.com/github/Javier-619/unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

javier sandoval perez - 24 de septiembre de 2025 - practica 6 - cortar arreglo numpy

slice en python significa tomar elementos de de un indice determinando a otro indice

Pasamos slice en lugar del indice de esta manera :[start:end]
si no pasamos el inicio se considera 0
si no pasamos el final, su longitud es cinsiderada una matriz de una dimension
-------------
Ejemplo:([1,2,3,4,5,6,7])
cortar los elementos del indice 1 al indice 5
-------------


In [1]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6,7])

print(arreglo[1:5])

[2 3 4 5]


Ejemplo2:
([1,2,3,4,5,6,7])
cortar del indice 4 hasta el final de la matriz

In [2]:
import numpy as np

arreglo = np.array ([1,2,3,4,5,6,7])

print(arreglo[4:])

[5 6 7]


 Ejemplo3:
 ([1,2,3,4,5,6,7])
 cortar elementos desde el principio hasta el indice 5


In [3]:
import numpy as np

arreglo = np.array ([1,2,3,4,5,6,7])

print(arreglo[:5])

[1 2 3 4 5]


Ejemplo4:
([1,2,3,4,5,6,7])
Corte negativo. utilizamos el operador "menos" para hacer referencia a un indice desde el final.
----------------------
cortar del indice 3 desde el final al indice 1 desde el final

In [4]:
import numpy as np

arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[-3:-1])

[5 6]
