<a href="https://colab.research.google.com/github/Javier-619/unidad1/blob/main/practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

javier sandoval perez -practica7-25 de septiembre de 2025.
--------------
Slicing numpy
--------------
utilice STEP para determinar el paso del corte:

Ejemplo: ([1,2,3,4,5,6,7]) - Devuelve todos los elementos del indice 1 al indice 5



In [2]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[1:5:2])

[2 4]


Elemplo2:
([1,2,3,4,5,6,7])
devuelve los elementos de la matriz

In [3]:
import numpy as np
arreglo =np.array([1,2,3,4,5,6,7])
print(arreglo[::2])


[1 3 5 7]


slice de matrices 2D
-----------------------
Ejemplo:([[1,2,3,4,5],[6,7,8,9,10]])
Del segundo elemento ,corte dal indice 1 al indice 4


In [6]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[1, 1:4])

[7 8 9]


Ejemplo4:([[1,2,3,4,5],[6,7,8,9,10]])
De ambos elementos devuelve el indoce 2


In [7]:
import numpy as np
arrelgo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(arreglo[0:2,2])

[3 8]


EJEMPLO:5
([[[1,2,3,4,5],[6,7,8,9,10]]])
de ambos elementos, corta el indice 1 al indice 4


In [8]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Ejercicio 1- Autonomo
¿Del siguiente arreglo cual es el resultado?
([1,2,3,4,5])
corta del 1er elemento al 6to elemento con paso 2

In [13]:
import numpy as np
arreglo = np.array ([1,2,3,4,5,6,7])
print(arreglo[0:6:2])

[1 3 5]
